### PR TITLE
Pull request to add V4 compatibility for the SQL store

### PR DESCRIPTION
**Pull request by mrtolkien**
I hope I didn't break everything.

### CODE REVIEW

**Review by Satrium — APPROVED** [review]
Those changes include a bunch of formating changes @jjmaldonis should take a look at.
All changes related to the update for v4 look good to me, and can be merged.

**Comment by jjmaldonis** [comment]
Four things I noticed before merging:

1) What is this `switcher` and the new `getType` that goes with it? I don't see it used anywhere.

2) The platform string may (sometimes?) need to be of length 7 based on this recent issue: https://github.com/RiotGames/developer-relations/issues/61

3) The filename `dataTypes.py` feels inconsistent with the rest of the file names. Maybe use `datatypes.py`.

4) Is the puuid truly only used in the summoner endpoint? If it's used elsewhere (even in GET requests if it's always required), we may want to add it to the DTO after it arrives.

**Comment by mrtolkien** [comment]
Indeed, the switcher/getType files was a prototype and not meant to be included. I've removed them in the latest commit.

I've updated the platform string. 

Regarding PUUID I replicated the previous behaviour, do you want me to add features? Maybe it's better to add/change features after it's added to the main branch? I'm weary of changing behaviour for an update.

**Comment by jjmaldonis** [comment]
Thanks!

**Pull request merged**
